### ISSUE TITLE
Not able to get it working

### ISSUE THREAD

**Issue by ragu-manjegowda** [alexander-born/bazel.nvim#1] opened 2023-04-07 08:49 UTC
I am trying to setup this plugin.

After installing it via Lazy, I do not see any of the plugin functions in command mode (:GoToBazelDefinition) inside a bazel project.

Pretty much followed your config, here is the change if it helps - https://github.com/ragu-manjegowda/config/commit/65ec76dc058c99ab485f6fa272148b550bc87155

Tried disabling lazy loading, bazel-cmp doesn't seem to work either.

Not sure if there are any pre-reqs I am missing.

Let me know if you want me to try anything.

**Comment by alexander-born** [comment] 2023-04-07 10:15
Hey,

Thanks for trying out the plugin.

`GoToBazelDefinition` is a vim function not a user command. So calling it from command mode would be `:call GoToBazelDefinition()`. Can you try if that works?


![nvim_goto_definition](https://user-images.githubusercontent.com/61082865/230593029-5414bfcc-c978-4332-82fc-a3e0c19cc372.gif)

**Comment by alexander-born** [comment] 2023-04-07 10:33
Auto completion is only triggered on the first `"` in a line.
After the first `"` it should start suggesting files in the path if the open BUILD file.
When typing `"//` it should start suggesting bazel labels.
Should look like this.
![nvim_autocomplete](https://user-images.githubusercontent.com/61082865/230594112-f1f56127-1eec-4fa6-bd6a-4e6ab16970a4.gif)

**Comment by alexander-born** [comment] 2023-04-07 10:46
Maybe `pynvim` dependency is missing. Can you check if this helps?
```
pip install pynvim
```

This should be visible when doing `:checkhealth`

There should be something like this
```
## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.10.6
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.
```

**Comment by ragu-manjegowda** [comment] 2023-04-07 19:01
Thank you so much for the quick response.

```
:call GoToBazelDefinition().
```
^^This, sorry my bad.

```
Auto completion is only triggered on the first " in a line.
```
This works too! Is it possible to have completion show up in command mode? Like when we try to run a target with `:Bazel run //`. Bazel completion on zsh is insanely slow having this will be super useful.

##### `BazelGetCurrentBufTarget()` seems to gives an error,
In your example call it from `reactions.cpp`. In my case `cc_library` is custom rule defined in `defs`. Let me know if you want me to create a separate bug for this.

Thanks again for this amazing plugin!

**Comment by alexander-born** [comment] 2023-04-07 19:25
Completion in command mode when using `:Bazel run //` works for me. But this has nothing to do with this plugin. It uses the bash completion script from Bazel itself. This is done by the official Bazel plugin. See https://github.com/bazelbuild/vim-bazel/issues/18

**Comment by alexander-born** [comment] 2023-04-07 19:28
`BazelGetCurrentBufTarget()` is not meant to be called from a BUILD file. But rather a source file. It will use Bazel queries to get the Bazel target for this source file.

**Comment by alexander-born** [comment] 2023-04-07 19:29
Can you elaborate what does not work for BazelGetCurrentBufTarget()?

**Comment by alexander-born** [comment] 2023-04-07 19:39
I forgot to add the keymaps in the readme. Maybe these help you. https://github.com/alexander-born/nvim/blob/e23a01c9b531b2bf2bef4cb18e1bc2756d01c518/lua/config/keymaps.lua#L30-L43

**Comment by ragu-manjegowda** [comment] 2023-04-07 20:39
>Can you elaborate what does not work for BazelGetCurrentBufTarget()?

I opened a `.cpp` file and ran this -> `:call BazelGetCurrentBufTarget()`

This is the error I got, it did not take me to or print the bazel target name.

```
Error detected while processing function BazelGetCurrentBufTarget[1]..provider#python3#Call:
line   18:
Error invoking 'python_eval' on channel 3 (python3-script-host):
error caught in request handler 'python_eval ['bazel_vim.get_bazel_target()']':
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pynvim/plugin/script_host.py", line 167, in python_eval
    return eval(expr, self.module.__dict__)
  File "<string>", line 1, in <module>
  File "/Users/ragu/.local/share/nvim/lazy/bazel.nvim/plugin/bazel_vim.py", line 65, in get_bazel_target
    bazel_file_label = bazel_query(f"{fname_rel}", ws_root)
  File "/Users/ragu/.local/share/nvim/lazy/bazel.nvim/plugin/bazel_vim.py", line 45, in bazel_query
    return subprocess.check_output(command.split(" "), cwd = ws_root).decode("utf-8").strip("\n")
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'query', 'src/xx.cpp', '--color', 'no', '--curses', 'no', '--noshow_progress']' returned
 non-zero exit status 6.
```

**Comment by alexander-born** [comment] 2023-04-07 20:46
I can't reproduce without access to the codebase, so you need to help me out here. It says the Bazel query failed. Can you run the following in a shell:
```
bazel query src/dw/sensors/lidar/impl/LidarSocket.cpp --color no --curses no --noshow_progress
```

**Comment by ragu-manjegowda** [comment] 2023-04-07 21:39
That explains it, thank you! One suggestion, worth catching the error message and displaying it.

I am using docker to run bazel, is it possible to specify the path for the plugin to use instead of defaulting to `bazel`?

Something like this for LSP,
```
lspconfig.pyright.setup {
  cmd = {
    "docker",
    "exec",
    "-i",
    "my-container",
    "pyright-langserver",
    "--stdio",
  }
}

```

**Comment by ragu-manjegowda** [comment] 2023-04-08 02:24
Found it. This should work as long as this plugin is based on `vim-bazel` - https://github.com/bazelbuild/vim-bazel/blob/master/doc/bazel.txt#L45

Thanks a lot!

**Comment by alexander-born** [comment] 2023-04-08 18:45
Ok you can now set `vim.g.bazel_cmd` to change the to your docker cmd. I will close this issue now! Please let me know if you still have issues.

See: https://github.com/alexander-born/bazel.nvim/commit/d7fa192aebe3a605dd30ce1623b34afc6e9160f3

**Closed as completed by alexander-born** 2023-04-08 18:45 UTC

**Comment by alexander-born** [comment] 2023-04-08 18:53
BTW I removed the deprecated vim functions, use the lua functions instead. See https://github.com/alexander-born/bazel.nvim/commit/8398aa10928881e7ccfd9c2d92af7ede5a18abbb

**Comment by ragu-manjegowda** [comment] 2023-04-09 00:12
Neat! Thank you!
